version: '3'
services:
  php-fpm:
    restart: always
    build: ./docker/php
#    ports:
#      - "9000:9000"
    volumes:
      - ./:/var/www/html
    links:
      - mysql
#    networks:
#      - default

  gusbot:
    restart: always
    build: ./docker/gusbot
    volumes:
      - ./:/var/www/html
  #    - ./config.js:/usr/src/app/config.js
    links:
      - redis
      - php-fpm
      - mysql

  redis:
    image: redis:latest
    volumes:
      - ./docker/redis:/data

  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    links:
      - redis
      - php-fpm
      - mysql
    volumes:
#     - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
#     - ./.htpasswd:/etc/nginx/.htpasswd
#     - ./docker/nginx/cert/nginx.crt:/etc/nginx/ssl/nginx.crt
#     - ./docker/nginx/cert/nginx.key:/etc/nginx/ssl/nginx.key
#    networks:
#      - default

  mysql:
    restart: always
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "127.0.0.1:3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    networks:
      - default

  node:
    restart: always
    build: ./docker/node
    volumes:
      - ./:/var/www/html
#
#networks:
#  gusbot:
#    external:
#      name: gusbot